### ISSUE TITLE
Update Delivery 10 

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/gaza-israel-conflict-impact-analysis#56]
This tracks the **Delivery 10**, which includes:

```[tasklist]
### Tasks
- [ ] https://github.com/datapartnership/gaza-israel-conflict-impact-analysis/issues/57
- [ ] https://github.com/datapartnership/gaza-israel-conflict-impact-analysis/issues/58
- [ ] https://github.com/datapartnership/gaza-israel-conflict-impact-analysis/issues/59
```
